name: CI/CD for Gemini Chatbot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting
        run: |
          pip install flake8
          flake8 qa_chatbot.py --count --show-source --statistics

      - name: Build Docker Image
        run: |
          docker build -t gemini-chatbot .
        
      - name: Run Tests (if you add test scripts)
        run: echo "Tests will be added later"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gemini-chatbot .
          docker tag ${{ secrets.DOCKER_USERNAME }}/gemini-chatbot ${{ secrets.DOCKER_USERNAME }}/gemini-chatbot:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gemini-chatbot:latest